order = ["audio", "battery", "cpu_load", "network", "time"]
separator = "    "

[audio]
control = "Master"
mute = "ﱝ"
template = "{ICO} {VOL}%"
icons = ["奄", "奔", "墳"]

[backlight]
device = "intel_backlight"
template = "L {BL}%"
icons = []

[battery]
charging = "▲"
discharging = "▼"
enable_notifier = true
notifier_critical = 10
notifier_levels = [2, 5, 10, 15, 20]
separator = " · "
no_battery = ""
icons = ["", "", "", "", "", "", "", "", "", "", ""]

[cpu_load]
template = "{CL1} {CL5} {CL15}"
update_interval = 20

[network]
no_value = "NA"
template = "{IPv4} · {ESSID}"

[time]
format = "%Y-%m-%d %H:%M"
update_seconds = false
