order = ["audio", "cpu_load", "network", "time", "battery", "keymap"]
separator = "  î‚³  "

[audio]
control = "Master"
mute = "ğŸ”‡"
template = "{ICO} {VOL}%"
icons = ["ğŸ”ˆ", "ğŸ”‰", "ï’…"]

[backlight]
device = "intel_backlight"
template = "L {BL}%"
icons = []

[battery]
charging = "âš¡"
discharging = "â–¼"
enable_notifier = true
notifier_critical = 10
notifier_levels = [2, 5, 10, 15, 20]
separator = " Â· "
no_battery = "ï"
icons = ["ï–", "ï•¹", "ï•º", "ï•»", "ï•¼", "ï•½", "ï•¾", "ï•¿", "ï–€", "ï–", "ğŸ”‹"]

[cpu_load]
template = "{CL1} {CL5} {CL15}"
update_interval = 20

[network]
no_value = "NA"
template = "ğŸŒ {IPv4} ğŸ“¶ {ESSID}"

[time]
format = "ğŸ“… %Y-%m-%d ï™ %H:%M"
update_seconds = false

[keymap]
template = "{FLAG}"
flags = ["ó¾“¦", "ó¾“¬"]
